MARGINS = 5

DARKSTYLE = r"./res/darkthese.qss"
WHITESTYLE = r"./res/whitethese.qss"


#FramlessWindow
WINDOW_DEFAULT_WIDTH = 1250
WINDOW_DEFAULT_HEIGHT = 780


TITLE_BAR_HEIGHT = 35
TITLE_LABEL_SIZE = 35
TITLE_BUTTON_SIZE = 30
TITLE_ICON_SIZE = 20
#
