# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contractWin.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_contractWin(object):
    def setupUi(self, contractWin):
        contractWin.setObjectName("contractWin")
        contractWin.resize(400, 380)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(contractWin.sizePolicy().hasHeightForWidth())
        contractWin.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(contractWin)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 61, 16))
        self.label.setObjectName("label")
        self.contractCodeLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.contractCodeLineEdit.setGeometry(QtCore.QRect(110, 20, 131, 20))
        self.contractCodeLineEdit.setObjectName("contractCodeLineEdit")
        self.select = QtWidgets.QPushButton(self.centralwidget)
        self.select.setGeometry(QtCore.QRect(270, 20, 51, 23))
        self.select.setObjectName("select")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 55, 54, 12))
        self.label_2.setObjectName("label_2")
        self.kLineTypeComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.kLineTypeComboBox.setGeometry(QtCore.QRect(110, 50, 121, 22))
        self.kLineTypeComboBox.setObjectName("kLineTypeComboBox")
        self.kLineTypeComboBox.addItem("")
        self.kLineTypeComboBox.addItem("")
        self.kLineTypeComboBox.addItem("")
        self.kLineTypeComboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 54, 12))
        self.label_3.setObjectName("label_3")
        self.kLinePeriodComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.kLinePeriodComboBox.setGeometry(QtCore.QRect(110, 83, 111, 22))
        self.kLinePeriodComboBox.setObjectName("kLinePeriodComboBox")
        self.kLinePeriodComboBox.addItem("")
        self.kLinePeriodComboBox.addItem("")
        self.kLinePeriodComboBox.addItem("")
        self.kLinePeriodComboBox.addItem("")
        self.kLinePeriodComboBox.addItem("")
        self.kLinePeriodComboBox.addItem("")
        self.kLinePeriodComboBox.addItem("")
        self.kLinePeriodComboBox.addItem("")
        self.kLinePeriodComboBox.addItem("")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 120, 351, 161))
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setObjectName("groupBox")
        self.AllkLineRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.AllkLineRadioButton.setGeometry(QtCore.QRect(30, 27, 89, 31))
        self.AllkLineRadioButton.setObjectName("AllkLineRadioButton")
        self.startDateRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.startDateRadioButton.setGeometry(QtCore.QRect(30, 57, 89, 31))
        self.startDateRadioButton.setObjectName("startDateRadioButton")
        self.startDateLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.startDateLineEdit.setGeometry(QtCore.QRect(110, 63, 71, 20))
        self.startDateLineEdit.setObjectName("startDateLineEdit")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(190, 55, 121, 31))
        self.label_4.setObjectName("label_4")
        self.qtyRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.qtyRadioButton.setEnabled(True)
        self.qtyRadioButton.setGeometry(QtCore.QRect(30, 90, 89, 31))
        self.qtyRadioButton.setChecked(True)
        self.qtyRadioButton.setObjectName("qtyRadioButton")
        self.qtylineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.qtylineEdit.setGeometry(QtCore.QRect(110, 96, 51, 20))
        self.qtylineEdit.setObjectName("qtylineEdit")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(170, 90, 54, 31))
        self.label_5.setObjectName("label_5")
        self.historyRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.historyRadioButton.setGeometry(QtCore.QRect(30, 120, 111, 31))
        self.historyRadioButton.setObjectName("historyRadioButton")
        self.confirm = QtWidgets.QPushButton(self.centralwidget)
        self.confirm.setGeometry(QtCore.QRect(260, 291, 50, 25))
        self.confirm.setObjectName("confirm")
        self.cancel = QtWidgets.QPushButton(self.centralwidget)
        self.cancel.setGeometry(QtCore.QRect(330, 291, 50, 25))
        self.cancel.setObjectName("cancel")
        contractWin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(contractWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 23))
        self.menubar.setObjectName("menubar")
        contractWin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(contractWin)
        self.statusbar.setObjectName("statusbar")
        contractWin.setStatusBar(self.statusbar)

        self.retranslateUi(contractWin)
        self.kLineTypeComboBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(contractWin)

    def retranslateUi(self, contractWin):
        _translate = QtCore.QCoreApplication.translate
        contractWin.setWindowTitle(_translate("contractWin", "商品属性"))
        self.label.setText(_translate("contractWin", "商品代码："))
        self.select.setText(_translate("contractWin", "选择"))
        self.label_2.setText(_translate("contractWin", "K线类型："))
        self.kLineTypeComboBox.setItemText(0, _translate("contractWin", "分笔"))
        self.kLineTypeComboBox.setItemText(1, _translate("contractWin", "秒"))
        self.kLineTypeComboBox.setItemText(2, _translate("contractWin", "分钟"))
        self.kLineTypeComboBox.setItemText(3, _translate("contractWin", "日线"))
        self.label_3.setText(_translate("contractWin", "K线周期："))
        self.kLinePeriodComboBox.setItemText(0, _translate("contractWin", "1"))
        self.kLinePeriodComboBox.setItemText(1, _translate("contractWin", "2"))
        self.kLinePeriodComboBox.setItemText(2, _translate("contractWin", "3"))
        self.kLinePeriodComboBox.setItemText(3, _translate("contractWin", "5"))
        self.kLinePeriodComboBox.setItemText(4, _translate("contractWin", "10"))
        self.kLinePeriodComboBox.setItemText(5, _translate("contractWin", "15"))
        self.kLinePeriodComboBox.setItemText(6, _translate("contractWin", "30"))
        self.kLinePeriodComboBox.setItemText(7, _translate("contractWin", "60"))
        self.kLinePeriodComboBox.setItemText(8, _translate("contractWin", "120"))
        self.groupBox.setTitle(_translate("contractWin", "运算起始点"))
        self.AllkLineRadioButton.setText(_translate("contractWin", "所有K线"))
        self.startDateRadioButton.setText(_translate("contractWin", "起始日期"))
        self.label_4.setText(_translate("contractWin", "格式(YYYYMMDD)"))
        self.qtyRadioButton.setText(_translate("contractWin", "固定根数"))
        self.qtylineEdit.setText(_translate("contractWin", "2000"))
        self.label_5.setText(_translate("contractWin", "根"))
        self.historyRadioButton.setText(_translate("contractWin", "不执行历史K线"))
        self.confirm.setText(_translate("contractWin", "确认"))
        self.cancel.setText(_translate("contractWin", "取消"))
